blocksense-network/blocksense

apps/docs.blocksense.network/app/docs/contracts/integration-guide/using-data-feeds/chainlink-proxy/page.mdx
apps/docs.blocksense.network/app/docs/contracts/integration-guide/using-data-feeds/feed-registry/page.mdx
apps/docs.blocksense.network/app/docs/contracts/integration-guide/using-data-feeds/historic-data-feed/page.mdx
apps/docs.blocksense.network/app/docs/programming-languages-rnd/noir-plonky2-backend/page.mdx
apps/docs.blocksense.network/components/DeployedContracts/DeployedContracts.tsx
apps/docs.blocksense.network/components/common/Callout.tsx

- **Type**: `"default" | "error" | "info" | "warning"`
- **Description**: Defines the type of the callout. The `type` determines the background color, border color, and emoji (info, error, warning, or default). If not provided, the default type (`'default'`) is used.
- **Type**: `string | ReactElement`
- **Description**: The emoji or icon to be displayed next to the callout. If not provided, the default emoji for the specified `type` is used. You can pass a custom emoji or a React component here.
- **Description**: The title to be displayed at the top of the callout. This is optional and will be rendered if provided.
- **Type**: `ReactNode`
- **Description**: The content to be displayed inside the callout. This is the main content of the callout. …

feat(docs.ws|refactor.ui): Add common Callout component

---

apps/docs.blocksense.network/components/ui/DataTable/DataTableViewOptions.tsx
libs/ts/ui/assets/icons/chevron-right.svg
libs/ts/ui/assets/icons/circle.svg
libs/ts/ui/package.json
libs/ts/ui/src/components/DropdownMenu/DropdownMenu.stories.tsx
libs/ts/ui/src/components/DropdownMenu/DropdownMenu.tsx
libs/ts/ui/src/components/DropdownMenu/index.tsx

- Moved `DropdownMenu.tsx` from `apps/docs.blocksense.network/components/common/` to `libs/ts/ui/src/components/DropdownMenu/`.
- Added an `index.tsx` file in the `DropdownMenu` folder to simplify exports.
- Updated `libs/ts/ui/src/index.tsx` to reflect these changes.
- Created `DropdownMenu.stories.tsx` to document and test the DropdownMenu component in Storybook.
- Modified `package.json` in `libs/ts/ui` to update the exports accordingly for the DropdownMenu component.
- Updated references in `apps/docs.blocksense.network/components/DataTable/DataTableViewOptions.tsx`

[docs.ws/ui]: Migrate `DropdownMenu` and add story

---

libs/ts/contracts/tasks/multichain-deploy.ts

refactor(multichain-deploy): `multichain-deploy` works with new config

---

apps/docs.blocksense.network/components/sol-contracts/ABIModal/ABIModal.tsx
libs/ts/ui/package.json
libs/ts/ui/src/components/Drawer/Drawer.stories.tsx
libs/ts/ui/src/components/Drawer/Drawer.tsx
libs/ts/ui/src/components/Drawer/index.tsx
libs/ts/ui/src/index.tsx

- Deleted `components/common/Drawer.tsx` as it is no longer needed.
- Modified `components/sol-contracts/ABIModal/ABIModal.tsx` to remove references to the deleted Drawer component and integrate the new dropdown-based UI.
- Modified `../../libs/ts/ui/package.json` to update the exports and dependencies.
- Updated `../../libs/ts/ui/src/index.tsx` to reflect the changes in the UI component structure.
- Added a new `Drawer/` folder under `../../libs/ts/ui/src/components/`.
- The new Drawer implementation is now located in `../../libs/ts/ui/src/components/Drawer/`.
- This version replaces the previous implementation and aligns with the latest UI patterns.
- The new Drawer component includes updated documentation and stories in Storybook.
- The integration ensures better modularity and …

[ui]: Migrate Drawer component to Storybook

---

apps/data-feeds-config-generator/src/data-services/chainlink_feeds.ts
apps/data-feeds-config-generator/src/data-services/types.ts
apps/data-feeds-config-generator/src/feeds-config/data-providers.ts
apps/data-feeds-config-generator/src/feeds-config/index.ts
config/chainlink_compatibility_new.json
config/feeds_config_new.json
libs/ts/config-types/src/data-feeds-config/index.ts

- **Updated feeds config** to reflect the latest adjustments.  
- **Implemented filtering logic** to exclude data feeds with **inconsistent Chainlink data**.  
- **Refactored filtering mechanism** to prevent the removal of **RefPrice** CL data feeds.  
- **Remove non crypto data feeds**
- **Remove CL `Pegged Asset` data feeds**
- **Remove CL hidden data feeds**
- **Ignore case when checking if pair is supported by CEX**

[DFCG]: Remove CL doc inconsistent feeds. Add CL RefPrice data feeds. Remove sus stuff.

---

apps/docs.blocksense.network/components/sol-contracts/ABIModal/ABIModal.tsx
libs/ts/ui/package.json
libs/ts/ui/src/components/ScrollArea/ScrollArea.stories.tsx
libs/ts/ui/src/components/ScrollArea/ScrollArea.tsx
libs/ts/ui/src/components/ScrollArea/index.tsx
libs/ts/ui/src/index.tsx

- Updated `apps/docs.blocksense.network/components/sol-contracts/ABIModal/ABIModal.tsx`:
- Made necessary adjustments to the ABIModal component for improved functionality.
- Modified `libs/ts/ui/package.json` to reflect new dependencies and exports.
- Modified `libs/ts/ui/src/index.tsx` to ensure the ABIModal component and other relevant components are properly exported.
- Introduced a new `ScrollArea` component under `libs/ts/ui/src/components/ScrollArea/`:
- The component enhances the user experience by offering smooth scrolling for content-heavy sections.

[ui]: Migrate ScrollArea component to Storybook

---

nix/modules/sequencer/backends/process-compose.nix
nix/pkgs/default.nix

Coauthored with: Martin Nikov <mnikov12@gmail.com>

feat(nix/process-compose): Added readers for kafka topics used by sequencer/reporters

---

libs/ts/ui/package.json
libs/ts/ui/src/components/ProgressBar/ProgressBar.stories.tsx
libs/ts/ui/src/components/ProgressBar/ProgressBar.tsx
libs/ts/ui/src/components/ProgressBar/index.tsx
libs/ts/ui/src/index.tsx

- Modified `../../libs/ts/ui/package.json` to update the exports and dependencies to include the `ProgressBar` component.
- Updated `../../libs/ts/ui/src/index.tsx` to reflect the changes in the component structure, ensuring the `ProgressBar` is properly exported and ready for use.
- New stories were added for the `ProgressBar` component in Storybook, allowing for interactive exploration of different states of the component.
- The documentation now includes examples for the determinate progress bar, indeterminate spinner, and a fullscreen loading spinner.
- Updated exports in `../../libs/ts/ui/src/index.tsx` to include the `ProgressBar` component.
- Ensured seamless transition by modifying relevant imports across the codebase, allowing for easier access and consistent usage of the …

[ui]: Migrate ProgressBar component to Storybook

---

apps/docs.blocksense.network/components/common/Slider.tsx

- **Type**: `number`
- **Description**: The current value of the slider. This controls the position of the thumb. If not provided, the default value is `0`.
- **Type**: `number`
- **Description**: The minimum value the slider can have. Default is `0`.
- **Type**: `number`
- **Description**: The maximum value the slider can have. Default is `100`.
- **Type**: `number`
- **Description**: The step increment for the slider value. Default is `1`.
- **Type**: `'line' | 'dot'`
- **Description**: Determines the style of the ticks on the slider. `"line"` gives vertical lines, while `"dot"` gives small round dots.
- **Description**: Additional utility classes for styling the slider container.
- **Type**: `(value: number) => void`
- **Description**: A callback function that is …

feat(docs.ws|refactor.ui): Add common Slider component

---

libs/ts/ui/package.json
libs/ts/ui/src/components/Slider/Slider.stories.tsx
libs/ts/ui/src/components/Slider/Slider.tsx
libs/ts/ui/src/components/Slider/index.tsx
libs/ts/ui/src/index.tsx

- Modified `../../libs/ts/ui/package.json` to update the exports and dependencies to include the `Slider` component.
- Updated `../../libs/ts/ui/src/index.tsx` to reflect the changes in the component structure, ensuring the `Slider` is properly exported and ready for use.
- New stories were added for the `Slider` component in Storybook, allowing for interactive exploration of different configurations.
- The documentation now includes examples for the basic slider, tick-based sliders, wide-range selection, small-step increments, and high-precision adjustments.
- Updated exports in `../../libs/ts/ui/src/index.tsx` to include the `Slider` component.
- Ensured seamless transition by modifying relevant imports across the codebase, allowing for easier access and consistent usage of the …

[ui]: Migrate Slider component to Storybook

---

apps/docs.blocksense.network/components/ui/DataTable/DataTableFacetedFilter.tsx
libs/ts/ui/assets/icons/search.svg
libs/ts/ui/package.json
libs/ts/ui/src/components/Command/Command.stories.tsx
libs/ts/ui/src/components/Command/Command.tsx
libs/ts/ui/src/components/Command/index.tsx
libs/ts/ui/src/index.tsx
yarn.lock

- Added `cmdk` dependency to `../../libs/ts/ui/package.json`, ensuring the necessary package is included for the Command component functionality.
- Migrated the `Command` component to Storybook, allowing for easy testing and exploration of different configurations.
- Updated the import for the `Command` component in `DataTableFacetedFilter` to ensure compatibility and seamless integration with the latest updates.
- New stories were added for the `Command` component in Storybook, allowing for interactive exploration of different configurations.
- Updated Storybook styles to ensure consistency and a better visual experience for users working with the `Command` component.
- Ensured the `Command` component is properly exported and integrated into the relevant parts of the codebase.
- Modified …

[ui]: Migrate Command component to Storybook 

---

apps/trigger-oracle/src/lib.rs

Fixes #1035.
Tested on top of 867da3db09eebb65258d3af7023b019256939df7.
Sample message that shows up after the change:
```
2025-03-14T12:33:41.399888Z ERROR trigger_oracle: Oracle script runner terminated with error: Ok(Other("Oracle execution loop terminated"))
```

feat(reporter-v2): Don't quit if OS runner stops

---

apps/sequencer/src/block_creator.rs
apps/sequencer/src/feeds/feed_slots_processor.rs
apps/sequencer/src/http_handlers/data_feeds.rs
nix/modules/sequencer/sequencer-opts.nix
nix/test-environments/example-setup-01.nix

Kudos to @HristoStaykov for the long hours of pair debugging only to understand all works fine!

[config]: Update `example-setup-01.nix` with new feeds

---

libs/feeds_processing/src/adfs_gen_calldata.rs

Hot fix of the hot fix in https://github.com/blocksense-network/blocksense/pull/1093
cc: @HristoStaykov

fix(feeds_processing/adfs_gen_calldata): Fix default stride

---

docs/spellbook.md

@blocksense-network/all Please review the content and feel free to add any information or insights that you find valuable based on your **day-to-day** tasks or development work.
- 🪄 Blocksense Spellbook
- Table of Contents
- Local Enviroment
- Starting and Stopping the Blocksense Local Environment
- Logs
- Reading On-Chain Data with `cast`
- Reading data from v1 contracts
- Using `UpgradeableProxy` contract
- Using `ChainlinkProxy` contract
- Reading data from ADFS contracts
- Using `UpgradeableProxyADFS` contract
- Using `CLAggregatorAdapter` contract
- Sequencer interaction
- Get information of effective sequencer configuration
- Get information of effective feeds configuration
- Get networks related information
- Production Environment

[docs]: Add initial version of `spellbook.md`

---

libs/ts/ui/package.json
libs/ts/ui/src/components/Form/Form.stories.tsx
libs/ts/ui/src/components/Form/Form.tsx
libs/ts/ui/src/components/Form/index.tsx
libs/ts/ui/src/index.tsx

- **Modified `../../libs/ts/ui/package.json`** to include necessary dependencies for the new `Form` components and ensure compatibility with the `FormContext` used in the new form structure.
- **New file `../../libs/ts/ui/src/components/Form/Form.tsx`**: A new `Form` component was created, featuring the ability to manage form state using context and handle submission, validation, and reset actions.
- **New file `../../libs/ts/ui/src/components/Form/Form.stories.tsx`**: A Storybook story was added for the `Form` component to provide an interactive demo of how the form behaves, including validation and submission handling.
- **New file `../../libs/ts/ui/src/components/Form/index.tsx`**: A new index file was added to properly export the form components, ensuring that they are easily …

[ui]: Migrate Form component to Storybook

---

apps/sequencer/src/providers/eth_send_utils.rs
libs/prometheus/src/metrics.rs

Let's do the data aggregation/visualization in the Prometheus UI, not in the metrics themselves.

feat(metrics): Switch metrics to gauge

---

apps/docs.blocksense.network/components/common/Checkbox.tsx

- **Type**: `ReactNode`
- **Description**: The child components (e.g., `Checkbox`) to be rendered inside the checkbox group.
- **Description**: The label text for the checkbox group. If provided, it will be rendered above the group.
- **Description**: Additional utility classes for styling the label of the checkbox group.
- **Description**: Additional utility classes for styling the checkbox group container.
- **Type**: `FieldsetHTMLAttributes<HTMLFieldSetElement>`
- **Description**: Any additional props that can be applied to the checkbox group container.
---
- **Description**: The value associated with this checkbox item. This value is used to determine whether the checkbox is selected.
- **Type**: …

[docs.ws]: Add common `Checkbox` component

---

apps/nft.blocksense.network/app/globals.css
apps/nft.blocksense.network/app/layout.tsx
apps/nft.blocksense.network/app/page.tsx
apps/nft.blocksense.network/components/NFTDrop.tsx
apps/nft.blocksense.network/config.ts
apps/nft.blocksense.network/next-env.d.ts
apps/nft.blocksense.network/package.json
apps/nft.blocksense.network/postcss.config.mjs
apps/nft.blocksense.network/src/index.ts
apps/nft.blocksense.network/tsconfig.json
yarn.lock

Global styles, including:
- **Dark mode styling**: This file includes CSS rules that support dark mode, ensuring the app adapts to the user's system preference.
- **Layout and typography adjustments**: Base styles for the layout (margins, padding, flexbox/grid settings) and typography (font family, sizes, line heights, etc.).
- **Responsive design**: Includes media queries to ensure that the app looks good on various screen sizes and devices.
Root layout for the NFT drop page:
- **SEO Metadata**: This file contains meta tags for improving the search engine optimization of the page, such as title, description, and Open Graph tags.
- **Header, footer, and main content structure**: Manages the structure for the header, footer, and general layout of the main content area of the page, ensuring …

feat(nft.blocksense.network) - Init workspace

---

apps/sequencer/src/aggregate_batch_consensus_processor.rs
apps/sequencer/src/feeds/votes_result_sender.rs
libs/config/src/lib.rs
libs/feeds_processing/src/adfs_gen_calldata.rs
libs/feeds_processing/src/utils.rs

Added test for validation function that will be used by reporter to validate a batch of aggregated updates.

test(sequencer/aggregation_consensus): Test the validate function with confirmable and non-confirmable batches of updates

---

apps/docs.blocksense.network/hooks/useHash.ts

Custom hook `useHash` to get and change hash in the URL quickly.

[docs.ws]: Implement `useHash` hook

---

apps/docs.blocksense.network/app/layout.tsx
apps/docs.blocksense.network/theme.config.tsx

[docs.ws]: Show og image and title

---

apps/docs.blocksense.network/components/common/DataTable/DataTableFacetedFilter.tsx
libs/ts/ui/package.json
libs/ts/ui/src/components/Checkbox/Checkbox.stories.tsx
libs/ts/ui/src/components/Checkbox/Checkbox.tsx
libs/ts/ui/src/components/Checkbox/index.tsx
libs/ts/ui/src/components/Dialog/Dialog.stories.tsx
libs/ts/ui/src/components/DropdownMenu/DropdownMenu.stories.tsx
libs/ts/ui/src/components/DropdownMenu/DropdownMenu.tsx
libs/ts/ui/src/index.tsx

This PR migrates the `Checkbox` component to `Storybook`, improving documentation and reusability across the project.
* Changes:
- Moved the `Checkbox` component from `@blocksense/docs.blocksense.network` to `@blocksense/ui`.
- Updated `package.json` and `index.tsx` to ensure proper exports.
- Added `Checkbox.stories.tsx` to `Storybook` for better component visualization.
- Refactor `DropdownMenuCheckboxItem.tsx` in `DropdownMenu.tsx` component to use our custom `Checkbox` component.
- Refactor `DataTableFacetedFilter.tsx` component to use our custom `Checkbox` component.
- Update `Dialog.stories.tsx` and `DropdownMenu.stories.tsx`.
* Why?
- This migration enhances maintainability and aligns with our UI component structure, ensuring consistent usage across projects.
* How to Test:
- Run …

[docs.ws/ui]: Migrate `Checkbox` component to `Storybook`

---

apps/nft.blocksense.network/app/globals.css
apps/nft.blocksense.network/app/typography/default.css
apps/nft.blocksense.network/app/typography/medium-large.css
apps/nft.blocksense.network/src/geist.ts

- Defined custom CSS variables for font sizes, line heights, and font families to be used globally across the project. This includes:
- `--font-size-h1`, `--font-size-h2`, `--font-size-body`, etc.
- `--line-height-h1`, `--line-height-h2`, `--line-height-body`, etc.
- Font families for both Geist and Geist Mono fonts.
**Mobile (Small Screens):**
- Introduced default typography for mobile devices. Paragraphs, headings (`h1`, `h2`, `h3`, `h4`), and links are styled with optimized font sizes, line heights, and spacing to ensure readability on smaller screens.
**Medium and Large Screens (min-width: 768px):**
- Applied responsive typography using media queries, enhancing text sizes and spacing for larger screens, ensuring consistency and readability for desktop and tablet views.
**Headings …

feat(nft.blocksense.network): Define typography - Blocksense NFT

---

apps/nft.blocksense.network/app/layout.tsx
apps/nft.blocksense.network/components/Navbar.tsx
apps/nft.blocksense.network/public/icons/close.svg
apps/nft.blocksense.network/public/icons/open.svg

Desktop:
Mobile - close:
Mobile - open:
- animation in open/close mobile navbar

[nft]: Implement desktop and mobile `Navbar`

---

apps/docs.blocksense.network/components/common/Carousel.tsx
apps/docs.blocksense.network/public/icons/chevron-left.svg
libs/ts/ui/assets/icons/chevron-left.svg
libs/ts/ui/package.json
libs/ts/ui/src/components/Button/Button.tsx
libs/ts/ui/src/components/Button/index.tsx
libs/ts/ui/src/components/Carousel/Carousel.tsx
libs/ts/ui/src/components/Carousel/index.tsx
libs/ts/ui/src/index.tsx

- **Type**: `'horizontal' | 'vertical'`
- **Default**: `'horizontal'`
- **Description**: Determines the scrolling direction of the carousel. Use `'horizontal'` for left-to-right scrolling or `'vertical'` for top-to-bottom scrolling.
- **Description**: Additional utility classes for styling the carousel container.
- **Type**: `ReactNode`
- **Description**: The child components (e.g., `CarouselContent`, `CarouselItem`) to be rendered inside the carousel.
- **Type**: `HTMLAttributes<HTMLDivElement>`
- **Description**: Any additional props that can be applied to the carousel container.
---
- **Description**: Additional utility classes for styling the carousel content container.
- **Type**: `ReactNode`
- **Description**: The child components (e.g., …

[docs.ws]: Add common `Carousel` component

---

apps/sequencer/src/feeds/feed_slots_processor.rs
libs/data_feeds/src/feeds_processing.rs
libs/prometheus/src/metrics.rs

Addressing https://github.com/blocksense-network/blocksense/pull/1148#discussion_r2018798906

fix(skip-reason): UnexpectedError should be a dont skip

---

apps/docs.blocksense.network/app/page.tsx
apps/docs.blocksense.network/config.ts

feat(docs.ws): Home page, update description

---

apps/nft.blocksense.network/app/design-system/colors.css
apps/nft.blocksense.network/app/design-system/typography/medium-large.css

- #2B2929 -> #262626
- Add default `white` color for H titles and input

[nft]: Update colors

---

apps/nft.blocksense.network/app/design-system/typography/default.css
apps/nft.blocksense.network/app/design-system/typography/medium-large.css

Add default colors for H titles and input, like for desktop.

[nft]: Fix default colors for mobile

---

apps/nft.blocksense.network/components/Footer.tsx
apps/nft.blocksense.network/components/Navbar.tsx

[nft]: Add `max-width` to Navbar & Footer and fixed link text

---

apps/nft.blocksense.network/app/error.tsx
apps/nft.blocksense.network/app/not-found.tsx

fix(nft.blocksense.network): 404 and 500 page updates

---

apps/nft.blocksense.network/app/layout.tsx

feat(nft.blocksense.network): Add og image to be the BS one

---

apps/nft.blocksense.network/app/layout.tsx
apps/nft.blocksense.network/app/page.tsx

Add GA Scripts to Blocksense NFT page.

feat(nft.blocksense.network): Add GA scripts and exchange sections

---

apps/nft.blocksense.network/components/About.tsx
apps/nft.blocksense.network/components/Form.tsx

In this Pr I execute requested updates for the NFT page:
- change the container size of the `About Header` for Desktop: max-width set to `28.875rem` `(462px)`
- change the `Form` title

[nft]: NFT page requested updates

---

apps/nft.blocksense.network/app/layout.tsx
apps/nft.blocksense.network/package.json
yarn.lock

Follow [ Next.js guide - Google Tag Manager](https://nextjs.org/docs/pages/guides/third-party-libraries#google-tag-manager)
- add `@next/third-parties`
- remove custom `GTM` components (using `dangerouslySetInnerHTML`)
- use `GoogleTagManager` component in `layout.tsx`

[nft]: Fix google analytics

---

apps/nft.blocksense.network/components/Hero.tsx

We do not want horizontal scrolling on mobile.
This PR aims to fix the issue.
* **Before:**
* **After:**

[nft]: Remove horizontal scrolling on mobile

---

apps/oracles/stock-price-feeds/src/lib.rs
apps/oracles/stock-price-feeds/src/utils.rs

Resolved comments from @Xearty on [PR:1290](https://github.com/blocksense-network/blocksense/pull/1290)

[oracles/stock-price-feeds]: Market hours

---

apps/oracles/stock-price-feeds/src/fetch_prices.rs
apps/oracles/stock-price-feeds/src/lib.rs
apps/oracles/stock-price-feeds/src/utils.rs

[oracles/stock-price-feeds]: Impove capabilities collection flow

---

apps/social-verification/package.json
package.json
yarn.lock

Describe the purpose of this pull request.
Please delete options that are not relevant.
List the changes you have made.
Please describe the tests that you ran to verify your changes,
or at least the manual procedure to exercise the new code.

build(yarn): Update `wrangler`: `4.13.0`, `3.109.2` -> `4.15.2`

---

apps/nft.blocksense.network/components/Navbar.tsx

[nft]: `Banner` over `MobileNavbar`

---

apps/social-verification/src/db-schema.sql
apps/social-verification/src/endpoints.ts

refactor(social-verification): Use `participants_unique` DB

---

apps/nft.blocksense.network/app/layout.tsx
apps/nft.blocksense.network/components/Form.tsx
apps/nft.blocksense.network/components/RestFrom.tsx

refactor(nft): Restore rest form

---

apps/oracles/gecko-terminal/spin.toml
apps/oracles/gecko-terminal/src/lib.rs
apps/trigger-oracle/README.md
config/feeds_config_v2.json

`apps/oracles/gecko-terminal$ spin up --build`
```
Starting oracle component - Gecko Terminal
🕛 All prices fetched in 702.931172ms
+---------+---------------+--------------------+---------+---------------------+------------------+---------------+--------------------------------------------+
| Feed ID |    Network    |        Name        | Reverse |     Price[USD]      |   Volume[USD]    | Enough volume |                    Pool                    |
+---------+---------------+--------------------+---------+---------------------+------------------+---------------+--------------------------------------------+
| 1000000 | monad-testnet | USDC / WMON        | true    |    2.88266607164462 | 648994.501494301 |           Yes | 0x264e9b75723d75e3c607627d8e21d2c758db4c80 |
| 1000000 | …
```

feat(oracles/gecko-terminal): Add price feeds - CHOG, MOYAKI, MOLANDAK

---

apps/nft.blocksense.network/app/layout.tsx
apps/nft.blocksense.network/components/Form.tsx
apps/nft.blocksense.network/components/NetworkLink.tsx
apps/nft.blocksense.network/components/RestFrom.tsx

[nft]: Finish the campaign

---

config/feeds_config_v2.json

In a pair session with @magnusahmad we updated names and descriptions of some data feeds

[feeds-config-v2]: Update `full_name` & `description` of some feeds

---

nix/modules/blocksense/backends/process-compose.nix
nix/test-environments/example-setup-03.nix

[BSN-3104: Add Fast-Mode Test Nix Setup](https://coda.io/d/_d6vM0kjfQP6#_tuk5j/r3104&view=full)

[nix]: Add fast mode test nix setup 

---

apps/chain-interactions/.changeset/config.json
apps/chain-interactions/.gitignore
apps/chain-interactions/.vscode/extensions.json
apps/chain-interactions/.vscode/settings.json
apps/chain-interactions/README.md
apps/chain-interactions/package.json
apps/chain-interactions/scripts/copy-package-json.ts
apps/chain-interactions/src/Cli.ts
apps/chain-interactions/src/bin.ts
apps/chain-interactions/test/Dummy.test.ts
apps/chain-interactions/tsconfig.json
apps/chain-interactions/tsconfig.scripts.json
apps/chain-interactions/tsconfig.src.json
apps/chain-interactions/tsconfig.test.json
apps/chain-interactions/tsup.config.ts
apps/chain-interactions/vitest.config.ts
yarn.lock

In later PRs the scripts from libs/ts/onchain-interactions/src/scripts will be moved here

[apps]: Init Onchain-Interactions workspace

---

apps/sequencer/bin/sequencer_runner.rs
apps/sequencer/src/lib.rs
apps/sequencer/src/pyroscope_profiler.rs
libs/config/src/lib.rs
nix/modules/blocksense/module-opts/config-files/sequencer-config.nix
nix/modules/blocksense/module-opts/sequencer/default.nix
nix/test-environments/example-setup-01.nix

In this PR we introduce the necessary parameters in the nix config, so that when nix generates configuration for the sequencer the sequencer_config.json file will contain a correct pyroscope section.

Configuration for pyroscope added in nix 

---

.github/workflows/ci.yml
flake.lock
flake.nix
nix/modules/blocksense/backends/process-compose.nix
nix/modules/blocksense/backends/systemd.nix
nix/modules/blocksense/module-opts/blama.nix
nix/modules/blocksense/module-opts/default.nix
nix/pkgs/blama/default.nix
nix/pkgs/default.nix
nix/test-environments/example-setup-01.nix

- **feat(nix): Add package for `blama`**
- **feat(nix): add `blama` to `process-compose`**

feat(nix): add `blama` package, run in `process-compose`

---

apps/oracles/stock-price-feeds/spin.toml
config/feeds_config_v2.json

[BSN-3273: Add LQD price feed.](https://coda.io/d/_d6vM0kjfQP6#_tuk5j/r3273&view=full)

[feeds_config_v2]: Add `LQD` price feed in `stock-price-feeds` oracle

---

config/evm_contracts_deployment_v2/base-mainnet.json
config/evm_contracts_deployment_v2/ethereum-mainnet.json
config/evm_contracts_deployment_v2/somnia-mainnet.json
libs/ts/base-utils/src/evm/networks.ts
libs/ts/contracts/tasks/deployment-utils/init-chain.ts

- **feat(base-utils/evm/networks): Add `somnia-mainnet`**
- **fix(contracts/tasks/multichain-deploy): Don't require private key when the deployer is ledger**
- **feat(evm_contracts_deployment_v2): Add `somnia-mainnet`**

feat/evm deployments/add somnia mainnet

---

apps/trigger-oracle/src/lib.rs

Co-authored-by: Antoni Dikov <antoni.dikov@gmail.com>

refactor(reporter/oracles): Refactor broadcast channels

---

.github/workflows/ci.yml
.github/workflows/on-main.yml

Added `NEXT_PUBLIC_VERIFICATION_API_KEY` and `NEXT_PUBLIC_VERIFICATION_API_URL`

[gh-actions]: Add docs.ws env for email form

---

Justfile
apps/e2e-tests/src/process-compose/e2e.spec.ts
apps/e2e-tests/src/process-compose/helpers.ts
apps/e2e-tests/src/process-compose/types.ts
nix/default.nix
nix/modules/blocksense/backends/process-compose.nix
nix/shells/pkg-sets/rust.nix
nix/test-environments/default.nix
scripts/install_trigger_oracle_plugin.sh

This change makes the behavior of commit de588974fc4ffebcbbe0d42d57487aab063c102f
configurable.

feat(nix): Add option to use nix derivations as well as cargo artifacts in process-compose

---

apps/changelog-generator/src/commands/list-feeds.ts
libs/ts/base-utils/package.json
libs/ts/base-utils/src/tty.ts
yarn.lock

- **fix(apps/changelog-generator/list-feeds): Filter non-deployed feeds**
- **fix(base-utils/tty/getTextWidth): Replace our hand-rolled impl w/ `string-width` npm library**
- **feat(changelog-generato): Ad markdown-list display mode**
```
yarn start list-feeds --network megaeth-testnet --display-mode=markdown-list
```
Deployed feeds on megaeth-testnet
* **WHYPE HypurrFi Borrow Rate** - [`0x21026b830b734b014981309d5AB20FdcC95595D5`](https://megaexplorer.xyz/address/0x21026b830b734b014981309d5AB20FdcC95595D5)
* https://docs.blocksense.network/docs/data-feeds/feed/102001#megaeth-testnet
* **wstHYPE HypurrFi Borrow Rate** - [`0xD6046f653e970F1fd370330F4304910325D996F6`](https://megaexplorer.xyz/address/0xD6046f653e970F1fd370330F4304910325D996F6)
* …

feat/changelog generator/add markdown list display mode

---

apps/oracles/forex-price-feeds/spin.toml
apps/oracles/forex-price-feeds/src/fetch_prices.rs
config/feeds_config_v2.json
libs/data_providers_sdk/src/price_data/fetchers/forex/fmp.rs
libs/data_providers_sdk/src/price_data/fetchers/forex/mod.rs
nix/test-environments/example-setup-01.nix

[BSN-3396: Implement FMP fetcher ](https://coda.io/d/_d6vM0kjfQP6#_tu4Kik5j/r3396&view=full)

[oracles/data_providers_sdk]: Implement `FMP` fetcher for forex oracle

---

libs/ts/contracts/tasks/deployment-utils/init-chain.ts
libs/ts/onchain-interactions/src/scripts/balance-script.ts
libs/ts/onchain-interactions/src/scripts/cost-calculations.ts

and fix colors in cost-calculations and balance scripts

[contracts]: Update Safe Fork deployer address to 0x215c513b1694Aa9D11069463FFCb3387A0a593a8

---

apps/oracles/borrow-rates/Cargo.toml
apps/oracles/cex-price-feeds/Cargo.toml
apps/oracles/commodities-price-feeds/Cargo.toml
apps/oracles/eth-rpc/Cargo.toml
apps/oracles/exsat-holdings/Cargo.toml
apps/oracles/forex-price-feeds/Cargo.toml
apps/oracles/gecko-terminal/Cargo.toml
apps/oracles/spout-rwa/Cargo.toml
apps/oracles/stock-price-feeds/Cargo.toml

[BSN-3438: Update oracles descriptions](https://coda.io/d/_d6vM0kjfQP6#_tu4Kik5j/r3438&view=full)

[oracles]: Update oracle descriptions

---

apps/sequencer/src/providers/eth_send_utils.rs

This PR introduces a call on the provider to get the "eth_getPriorityFee". When this field is not available, i.e. the provider returns an error, the network is considered **Legacy** and we proceed with `gas price` only.

fix(sequencer/eth_send_utils): Use both eth_getPriorityFee and eth_maxPriorityFeePerGas to decide on using legacy transactions

---

libs/ts/contracts/contracts/AggregatedDataFeedStore.sol
libs/ts/contracts/test/AggregatedDataFeedStore.test.ts

Currently, the sequencer can write whatever number that fits in 2b in the ring buffer table per feed id. This PR introduces modulo operation to ensure that the number written is not greater than `2^13 - 1`. Otherwise, when the number is above this maximum the client reading from the contract actually reads from another feed's storage.

Mod ring buffer indices before storage

---

libs/ts/base-utils/src/evm/networks.ts
libs/ts/onchain-interactions/src/scripts/cost-calculations.ts

And fix cost script for flare-coston and cyber-testnet

[base-utils]: Update api urls
