blocksense-network/blocksense

apps/sequencer/src/providers/provider.rs
A deluge of these prints overwhelms us at startup.
Let's at least make it easier to search in the code where they come from.
=> chore(prints): Add searchable string and change info to debug

apps/docs.blocksense.network/app/docs/contracts/integration-guide/using-data-feeds/chainlink-proxy/page.mdx, apps/docs.blocksense.network/app/docs/contracts/integration-guide/using-data-feeds/feed-registry/page.mdx, apps/docs.blocksense.network/app/docs/contracts/integration-guide/using-data-feeds/historic-data-feed/page.mdx, apps/docs.blocksense.network/app/docs/programming-languages-rnd/noir-plonky2-backend/page.mdx, apps/docs.blocksense.network/components/DeployedContracts/DeployedContracts.tsx, libs/ts/ui/package.json, libs/ts/ui/src/components/Callout/Callout.stories.tsx, libs/ts/ui/src/components/Callout/Callout.tsx, libs/ts/ui/src/components/Callout/index.tsx, libs/ts/ui/src/index.tsx
- Moved `Callout.tsx` from `apps/docs.blocksense.network/components/common/` to `libs/ts/ui/src/components/Callout/`.
- Added an `index.tsx` file in the `Callout` folder to simplify exports.
- Updated `libs/ts/ui/src/index.tsx` to reflect these changes.
- Created `Callout.stories.tsx` to document and test the `Callout` component in Storybook.
- Modified `package.json` in `libs/ts/ui` to update the exports accordingly for the `Callout` component.
- Updated the documentation files:
- `apps/docs.blocksense.network/app/docs/contracts/integration-guide/using-data-feeds/chainlink-proxy/page.mdx`
- `apps/docs.blocksense.network/app/docs/contracts/integration-guide/using-data-feeds/feed-registry/page.mdx`
- `apps/docs.blocksense.network/app/docs/contracts/integration-guide/using-data-feeds/histori …
=> [ui]: Migrate Callout component to Storybook

apps/docs.blocksense.network/components/ui/DataTable/DataTablePagination.tsx, libs/ts/ui/package.json, libs/ts/ui/src/components/Select/Select.stories.tsx, libs/ts/ui/src/components/Select/Select.tsx, libs/ts/ui/src/components/Select/index.tsx, libs/ts/ui/src/index.tsx
This PR migrates the `Select` component to `Storybook`, improving documentation and reusability across the project.
* Changes:
- Moved the `Select` component from `@blocksense/docs.blocksense.network` to `@blocksense/ui`.
- Updated `package.json` and `index.tsx` to ensure proper exports.
- Adjusted imports in `@blocksense/docs.blocksense.network` to reference `Select` from `@blocksense/ui`.
- Added `Select.stories.tsx` to `Storybook` for better component visualization.
* Why?
- This migration enhances maintainability and aligns with our UI component structure, ensuring consistent usage across projects.
* How to Test:
- Run `Storybook` and verify that the `Select` component renders correctly.
- Ensure existing imports and functionality remain intact after the update.
=> [ui]: Migrate `Select` component to `Storybook`

.gitignore, Justfile, apps/cli/src/spin_manifest.rs, nix/modules/sequencer/backends/process-compose.nix, nix/modules/sequencer/default.nix, nix/modules/sequencer/oracle-script-opts.nix, nix/modules/sequencer/reporter-opts-v2.nix, nix/pkgs/default.nix, nix/pkgs/oracle-script/default.nix, nix/test-environments/example-setup-01.nix
[![asciicast](https://asciinema.org/a/v1vXiFWYMEHSoDjWUJBLxrmTY.svg)](https://asciinema.org/a/v1vXiFWYMEHSoDjWUJBLxrmTY)
* Refactor the `nix/pkgs/oracle-script` derivation to make it possible to build both standalone oracle scripts and scripts part of the workspace
* Expose `crypto-price-feeds` oracle script
* Improve process-compose readiness start up time
* Fix small bugs and adjust git ignore
* Remove reporters-v1 from the example setup
* Change reporter-v2 working to `
- **feat(nix/pkgs): Expose `crypto-price-feeds` and allow building oracles parts of the workspace**
- **refactor(nix/pkgs): Remove `-wasm` pkg suffix**
- **config(git): Ignore `.wasm` and `.spin` dir**
- **fix(nix/modules/process-compose): Fix iteration over the old reporters**
- **fix(nix/modules/process-compose): …
=> feat(nix/process-compose): Complete reporter-v2 + crypto-price-feed oracle script setup

Cargo.lock, Cargo.toml, apps/oracles/gecko-terminal/Cargo.toml, apps/oracles/gecko-terminal/spin.toml, apps/oracles/gecko-terminal/src/lib.rs, apps/sequencer/src/http_handlers/admin.rs, config/feeds_config.json, libs/ts/config-types/src/data-feeds-config/index.ts, nix/pkgs/default.nix, nix/test-environments/example-setup-01.nix
Oracle for NOSTRA that fetches prices from Gecko Terminal, which provides information for dex prices
`scripts/sdk$ ./start-oracle-example.sh gecko_terminal`
```bash
2025-03-12T11:31:50.572762Z TRACE trigger_oracle: Triggering application: GeckoTerminal dex prices; component_id: gecko-terminal
2025-03-12T11:31:50.572767Z TRACE trigger_oracle: Calling handle oracle request for `gecko-terminal`
Starting oracle component - Gecko Terminal
Payload { values: [DataFeedResult { id: "607", value: Numerical(179.859758223554) }] }
2025-03-12T11:31:50.755463Z TRACE trigger_oracle: Oracle request for `gecko-terminal` completed in 182ms
```
=> feat(oracles): Implement price fetch from GeckoTerminal for dex pool

config/feeds_config.json, nix/filesets.nix
- config(feed_config_v1): Assign higher ids for `exsat` and `gecko-terminal` to make room for future feeds
- build(nix/filesets): Reduce rebuilds on json config files changes
=> gecko terminal post merge fixes

apps/docs.blocksense.network/components/common/Command.tsx, apps/docs.blocksense.network/components/common/Table.tsx, apps/docs.blocksense.network/components/ui/DataTable/DataTable.tsx, apps/docs.blocksense.network/components/ui/DataTable/DataTableFacetedFilter.tsx, apps/docs.blocksense.network/components/ui/popover.tsx, apps/docs.blocksense.network/lib/utils.ts, libs/ts/ui/package.json, libs/ts/ui/src/components/Accordion/Accordion.tsx, libs/ts/ui/src/components/Badge/Badge.tsx, libs/ts/ui/src/components/Button/Button.tsx, libs/ts/ui/src/components/Callout/Callout.tsx, libs/ts/ui/src/components/Card/Card.tsx, libs/ts/ui/src/components/Dialog/Dialog.tsx, libs/ts/ui/src/components/Drawer/Drawer.tsx, libs/ts/ui/src/components/DropdownMenu/DropdownMenu.tsx, libs/ts/ui/src/components/Input/Input.tsx, libs/ts/ui/src/components/Label/Label.tsx, libs/ts/ui/src/components/ScrollArea/ScrollArea.tsx, libs/ts/ui/src/components/Select/Select.tsx, libs/ts/ui/src/components/Switch/Switch.tsx, libs/ts/ui/src/components/Tabs/Tabs.tsx, libs/ts/ui/src/components/Tooltip/Tooltip.tsx, libs/ts/ui/src/index.tsx, libs/ts/ui/src/lib/utils.ts, libs/ts/ui/src/utils.ts
This PR introduces several changes related to the `utils.ts` services in the `@blocksense/ui` library. The idea behind these changes is to make the code clean and prevent code duplication by centralizing utility functions.
1. **Added**: `utils.ts` in `/libs/ts/ui/src/lib`.
2. **Updated**: `@blocksense/ui` to properly export `utils.ts`.
3. **Updated**: Component imports to use the new `utils.ts` location.
4. **Deleted**: `utils.ts` from `@blocksense/ui` as it is no longer needed.
5. **Deleted**: `utils.ts` from `@blocksense/docs.blocksense.network` as it is no longer needed.
- The `utils.ts` file is now located in `@blocksense/ui/src/lib`.
- The `@blocksense/ui` library has been updated to properly export `utils.ts`.
- Components have been updated to import utilities from the new location. …
=> [docs.ws/refactor.ui]: Organize `Utility Functions` to prevent `Code Duplication`

apps/data-feeds-config-generator/package.json, apps/data-feeds-config-generator/scripts/generate-feeds-config.ts, apps/data-feeds-config-generator/scripts/get-cmc-market-cap-data.ts, apps/data-feeds-config-generator/scripts/get-providers-data.ts, apps/data-feeds-config-generator/src/chainlink-compatibility/index.ts, apps/data-feeds-config-generator/src/data-services/artifacts-downloader.ts, apps/data-feeds-config-generator/src/data-services/chainlink_feeds.ts, apps/data-feeds-config-generator/src/data-services/fetchers/aggregators/cmc.ts, apps/data-feeds-config-generator/src/data-services/types.ts, apps/data-feeds-config-generator/src/feeds-config/data-providers.ts, apps/data-feeds-config-generator/src/feeds-config/index.ts, apps/data-feeds-config-generator/src/feeds-config/types.ts, config/chainlink_compatibility_new.json, config/feeds_config_new.json, yarn.lock
- Integrated artifacts from `blocksense-network/dfcg-artifacts` for better consistency.  
- Introduced scripts for fetching provider data and CoinMarketCap market cap data.
- Renamed `getOrCreateArtifact` → `createArtifact`, removing the logic to load existing artifacts.  
- Now, artifacts are prepared as an array instead of being written to files directly, improving log readability.  
- Reduced duplication of saved artifacts and improved artifact handling.  
- Filter out feeds with not exchanges arguments 
Removed feeds:
- "WSTETH / USD"
- "SUSDE / USD"
- "cbBTC / USD"
- "USD0 / USD"
- "USD0++ / USD"
- "ezETH / USD"
- "RLUSD / USD"
- "USDX / USD"
- "USDL / USD"
- "LUSD / USD"
- "DPI / USD"
- "AUSD / USD"
- "USR / USD"
- Update configs
Run:
```bash
cd apps/data-feeds-config-generator …
```
=> [DFCG]: DFCG reads artifacts from `blocksense-network/dfcg-artifacts`

Cargo.lock, apps/oracles/crypto-price-feeds/Cargo.toml, apps/oracles/crypto-price-feeds/src/lib.rs
```
. . .
🕛 All prices fetched in 3.274712744s
missing ids(id-symbol): [(439-SUSHI/ETH),(422-YFI/ETH),(32-wBTC/USD),(671-MLN/USDC),(566-USDtb/USD),(572-JOE/USDC),(567-USDtb/USDT),(339-deUSD/USDT),(338-deUSD/USD),(79-USDe/USDC),(679-PERP/USDC),(78-USDe/USDT),(76-USDe/USD),(34-wBTC/USDC),(33-wBTC/USDT),(683-GHST/USDC),(688-NULS/USDC),(669-MLN/ETH)]
(id-exchange_count): [(468-9),(107-3),(723-10),(526-1),(159-7),(67-8),(659-5),(174-3),(658-2),(672-6),(460-3),(629-5),(490-10),(548-11),(61-8),(166-14),(514-6),(259-7),(408-1),(637-10),(300-3),(114-18),(245-8),(450-5),(513-8),(258-8),(687-4),(200-10),(583-8),(290-5),(375-3),(387-10),(89-4),(364-12),(630-7),(638-7),(184-12),(198-3),(95-6),(100-10),(276-1),(235-4),(72-23),(266-3),(293-7),(398-3),(498-1),(21-10),(241-3),(275-7),(553-7),(467-3),(682-5 …
```
=> [oracles/crypto price feeds] Improve logs

apps/oracles/crypto-price-feeds/src/fetch_prices.rs
Before:
```
Missing pairs:
[{ 32: wBTC / USD },{ 688: NULS / USDC },{ 567: USDtb / USDT },{ 566: USDtb / USD },{ 572: JOE / USDC },{ 679: PERP / USDC },{ 78: USDe / USDT },{ 683: GHST / USDC },{ 79: USDe / USDC },{ 669: MLN / ETH },{ 339: deUSD / USDT },{ 439: SUSHI / ETH },{ 671: MLN / USDC },{ 34: wBTC / USDC },{ 33: wBTC / USDT },{ 76: USDe / USD },{ 422: YFI / ETH },{ 338: deUSD / USD },]
```
After:
```
Missing pairs:
[{ 671: MLN / USDC },{ 683: GHST / USDC },{ 669: MLN / ETH },{ 422: YFI / ETH },{ 572: JOE / USDC },{ 439: SUSHI / ETH },{ 679: PERP / USDC },{ 688: NULS / USDC },]
```
=> [oracles/crypto-price-feeds]: `symbol` in fill_results match symbol in exchanges

.github/workflows/ci.yml, apps/oracles/gecko-terminal/src/lib.rs, apps/sequencer/src/feeds/feed_allocator.rs, apps/sequencer/src/feeds/feed_slots_processor.rs, apps/sequencer/src/http_handlers/admin.rs, apps/sequencer/src/http_handlers/data_feeds.rs, apps/sequencer/src/providers/eth_send_utils.rs, libs/data_feeds/src/feeds_processing.rs, nix/shells/pkg-sets/pre-commit.nix
Fix warnings generated from clippy for unit tests. One warning was causing an assert in `test_get_feeds_config` to not perform the required check. Problem found by @Xearty - thanks for looking into this! 
To run cargo clippy on the unit tests run the following from the main blocksense project folder:
`cargo clippy --tests`
=> fix(tests): Make all unit tests pass clippy check

config/feeds_config_v2.json
To test if all works I start `process-compose` and try to read the on-chain data
```
cast call 0xee5a4826068c5326a7f06fd6c7cbf816f096846c --data 0x8000c350 --rpc-url http://127.0.0.1:8546 |  cut -c1-50 | cast to-dec
```
```
cast call 0xee5a4826068c5326a7f06fd6c7cbf816f096846c --data 0x8000c351 --rpc-url http://127.0.0.1:8546 |  cut -c1-50 | cast to-dec
```
```
cast call 0xee5a4826068c5326a7f06fd6c7cbf816f096846c --data 0x800186a0 --rpc-url http://127.0.0.1:8546 |  cut -c1-50 | cast to-dec
```
>  can be tested once https://github.com/blocksense-network/blocksense/pull/1078 is merged 
```
cast call 0xee5a4826068c5326a7f06fd6c7cbf816f096846c --data 0x800f4240 --rpc-url http://127.0.0.1:8546 |  cut -c1-50 | cast to-dec     
```
=> [config]: Add `ExSat BTC`, `USDT / WMON 0.2%` & pegged to 1 `USDC / USD` & `USDT / USD`

Cargo.lock, apps/sequencer/Cargo.toml, apps/sequencer/src/providers/eth_send_utils.rs, apps/sequencer/src/providers/provider.rs, apps/sequencer_tests/Cargo.toml, apps/sequencer_tests/bin/sequencer_tests.rs, libs/data_feeds/Cargo.toml, libs/feeds_processing/Cargo.toml, libs/feeds_processing/src/adfs_gen_calldata.rs, libs/gnosis_safe/Cargo.toml, libs/gnosis_safe/src/utils.rs, nix/shells/pkg-sets/pre-commit.nix
Most of the changed lines are in Cargo.lock. Actual change is only 102 lines (added/removed combined).
The dependency on `alloy-encode-packed` is removed, since it forces a transitive dependency on alloy 0.7.
The code from it is copied in and minimized to only the part that we're using.
Added a new field in Provider -- rpc_url -- to make it easy to extract the Url of an RPC provider. This is needed due to a change in the alloy API from 0.9 to 0.11 which hides the type of the transport (Http). An alternative would be to use dynamic casting, but I decided on this solution.
Cannot upgrade to alloy 0.12 due to following error in a dependency of alloy:
```
error[E0599]: no function or associated item named `hoodi` found for struct `alloy_chains::Chain` in the current scope
--> …
```
=> Remove alloy-encode-packed and upgrade alloy to 0.11

libs/ts/ui/package.json, libs/ts/ui/src/components/TextArea/TextArea.stories.tsx, libs/ts/ui/src/components/TextArea/TextArea.tsx, libs/ts/ui/src/components/TextArea/index.tsx, libs/ts/ui/src/index.tsx
This PR migrates the `TextArea` component to `Storybook`, improving documentation and reusability across the project.
* Changes:
- Moved the `TextArea` component from `@blocksense/docs.blocksense.network` to `@blocksense/ui`.
- Updated `package.json` and `index.tsx` to ensure proper exports.
- Adjusted imports in `@blocksense/docs.blocksense.network` to reference `TextArea` from `@blocksense/ui`.
- Added `TextArea.stories.tsx` to `Storybook` for better component visualization.
* Why?
- This migration enhances maintainability and aligns with our UI component structure, ensuring consistent usage across projects.
* How to Test:
- Run `Storybook` and verify that the `TextArea` component renders correctly.
- Ensure existing imports and functionality remain intact after the update.
=> [docs.ws/ui]: Migrate `TextArea` component to `Storybook`

nix/modules/sequencer/backends/process-compose.nix, nix/test-environments/example-setup-01.nix
- Introduced `ExSat BTC` and `WMON 0.2% / USDT`.
- Included USDT and USDC pegged feeds.
- `anvil-b` now forks `ink-sepolia` instead of `ethereum-holesky`.
- Now we support ADFS contract versions in the local env setup.
- `anvil-a` → `anvil-ethereum-sepolia`
- `anvil-b` → `anvil-ink-sepolia`
- Updated dependencies in `process-compose.nix` to reflect the new names.
To test if all works I start `process-compose` and try to read the on-chain data
- Read data for `USDT / USD Pegged` with id `50000`
```
cast call 0xee5a4826068c5326a7f06fd6c7cbf816f096846c --data 0x8000c350 --rpc-url http://127.0.0.1:8546 |  cut -c1-50 | cast to-dec
```
-  Read data for `USDC / USD Pegged` with id `50001`
```
cast call 0xee5a4826068c5326a7f06fd6c7cbf816f096846c --data 0x8000c351 --rpc-url http://127.0.0.1:8546 | …
```
=> [nix/example-setup-01]: Update once again

apps/docs.blocksense.network/components/common/Form.tsx
- **Description**: Additional utility classes for styling the form container.
- **Type**: `(values: Record<string, string | boolean | null>) => void`
- **Description**: A callback function that is triggered when the form is submitted with the form values.
- **Default**: `"Please fill out all required fields."`
- **Description**: The error message shown when required fields are missing.
- **Default**: `"Form submitted successfully!"`
- **Description**: The success message shown when the form is successfully submitted.
- **Description**: The name of the form field. This is used to identify and manage the field’s value in the form.
- **Description**: The label that will be displayed for …
=> feat(docs.ws|refactor.ui): Add common Form component 

nix/test-environments/example-setup-01.nix
While going through `process-compose`, me and @EmilIvanichkovv noticed that ink-sepolia's anvil fork fails to start from time to time. 
With this new url it seems more stable.
=> [nix/example-setup-01]: Update `ink-sepolia` fork URL

apps/docs.blocksense.network/public/icons/info.svg, libs/ts/ui/assets/icons/info.svg, libs/ts/ui/package.json, libs/ts/ui/src/components/InfoTip/InfoTip.tsx, libs/ts/ui/src/components/InfoTip/index.tsx, libs/ts/ui/src/components/Tooltip/Tooltip.tsx, libs/ts/ui/src/index.tsx
Used `Tooltip` & `Icon` components with `info.svg` to implement reusable and simpler component for more information with hover:
=> [ui/docs.ws]: Implement `InfoTip` component

apps/docs.blocksense.network/components/sol-contracts/AbsolutePath.tsx, apps/docs.blocksense.network/components/sol-contracts/ContractsFileTree.tsx
This PR adds or updates the links to our `contracts`, redirecting users to our `now-public GitHub repository`.
* **Before :**
* **After :**
=> [docs.ws]: Add Links to our Contracts on GitHub

apps/sequencer/src/feeds/feed_slots_processor.rs, apps/sequencer/src/providers/eth_send_utils.rs, apps/sequencer/src/providers/provider.rs, libs/data_feeds/src/feeds_processing.rs, libs/feeds_processing/src/utils.rs, libs/prometheus/src/metrics.rs
These metrics are only for the per-feed configuration.
We need a separate set for the per-feed + per-network configuration.
=> Adding skip-publishing metrics

.github/workflows/ci.yml, apps/nft.blocksense.network/next.config.ts
Configured GitHub Actions to deploy the Blocksense NFT project. This includes setting the project path to `apps/nft.blocksense.network/out`, naming the project `blocksense-nft`, and using the build command `yarn workspace @blocksense/nft.blocksense.network build`. A deployment output message was also added for visibility in CI logs.
=> ci(gh-actions): Add deployment for Blocksense NFT page

apps/nft.blocksense.network/src/geist.ts
This PR contains a quick, fix that refines how Geist and Geist Mono fonts are loaded using next/font/local, without the need of using weight and evaluate it directly from CSS variables, in the way they're defined.
=> fix(nft.blocksense.network): Update Geist and GeistMono font configuration 

apps/nft.blocksense.network/components/SocialNetworks.tsx
Replace Next.js `Link` component with `a` for external links in `SocialNetworks`
=> [nft]: Use `<a>` for external links - `SocialNetworks`

apps/docs.blocksense.network/public/icons/chevron-left.svg, libs/ts/ui/src/components/Carousel/Carousel.stories.tsx
This PR aims to add `Carousel stories` to our `Storybook`.
The `chevron-left.svg` icon is also deleted, as it is only used in the `ui library` and not in the `docs.ws` workspace.
=> [docs.ws/ui]: Create `Carousel stories` to our `Storybook`

libs/ts/contracts/@types/prettier-plugin-solidity.d.ts, libs/ts/contracts/tsconfig.json
This PR adds a missing type declaration for the `prettier-plugin-solidity` package and updates the `tsconfig.json` in the `contracts` library to include the newly added `@types` directory.
- Added a custom module declaration file: `@types/prettier-plugin-solidity.d.ts`
- Updated `tsconfig.json` to include `./@types` in the `include` section to ensure the declaration is picked up by the TypeScript compiler
This should prevent the following errors:
- In the ide  in the file `libs/ts/contracts/templates/encode-packed/index.ts` we see
- And during build:
=> [contracts]: Add type declaration for `prettier-plugin-solidity`

apps/oracles/crypto-price-feeds/spin.toml, apps/oracles/eth-rpc/spin.toml, apps/oracles/exsat-holdings/spin.toml, apps/oracles/gecko-terminal/spin.toml
This PR updates the `spin.toml` files for all oracles to match the structure introduced in [#814](https://github.com/blocksense-network/blocksense/pull/814). These changes are necessary for the oracles to function correctly when using the `just start-oracle <oracle>` command during local development.
- Updated `spin.toml` files for each oracle to conform to the latest schema.
- Format the `spin.toml` files
To catch issues like this earlier:
- We will incorporate a basic E2E check that runs `just start-oracle <oracle>` for all registered oracles and asserts they boot successfully.
- We should also document this requirement clearly when introducing future changes to the structure.
**Please be mindful when introducing changes like this in the future.**
They can silently break local workflows …
=> [oracles]: Make `just start-oracle <oracle>` great again

apps/nft.blocksense.network/components/Navbar.tsx
Requested by designers.
**Desktop:** 
>**Note**: This update will be applied to desktop only. For mobile, it will be, as it was before.
=> fix(nft.blocksense.network): Apply backdrop effect to main header

apps/sequencer/src/aggregate_batch_consensus_processor.rs, libs/feeds_processing/src/adfs_gen_calldata.rs, libs/feeds_processing/src/utils.rs
Fix in sequencer to correctly fill the values of the round counters that will be passed to the reporters before correction is made for the neighbors of the updated feed ids. 
Added a unit test to cover this scenario + refactor existing unit test to not use a hard coded tx_hash.
=> fix(sequencer/adfs): Fix round counters value correction for neighbors when sending to reporter

apps/nft.blocksense.network/components/Logo.tsx
- Replaced `next/link` with a standard `<a>` tag for the logo link.
- Moved the URL into a constant named `BLOCKSENSE_URL`.
- Added `target="_blank"` and `rel="noopener noreferrer"` to open the link in a new tab securely.
These changes align with best practices for handling external links in Next.js 15.
> Requested by marketing team.
=> refactor(nft.blocksense.network): Replace Next link with plain anchor in Logo component

apps/nft.blocksense.network/components/About.tsx, apps/nft.blocksense.network/components/CTA.tsx, apps/nft.blocksense.network/components/Footer.tsx, apps/nft.blocksense.network/components/Form.tsx, apps/nft.blocksense.network/components/Hero.tsx, apps/nft.blocksense.network/components/Navbar.tsx
In this PR we execute requested updates for the NFT page, including container size updates, copy updates requested by marketing, and CTA updates for mobile. The container sizes align with the specifications provided by the design team, and the copy changes reflect the latest marketing messaging.
- **Copy Updates**:
- Updated content in various sections to reflect the latest marketing messaging.
- Adjusted text for consistency with Blocksense's brand voice and marketing goals.
- **Container Sizes**:
- **Navbar**: max-width set to `71.25rem` (1140px)
- **Hero Section**: max-width set to `71.25rem` (1140px)
- **Hero NFT Image**: max-width set to `71.25rem` (1140px)
- **Form Block**: max-width set to `32.75rem` (524px)
- **About NFT Section**: max-width set to `59.125rem` (946px)
- **CTA …
=> feat(nft.blocksense.network): NFT page requested updates

Cargo.lock, apps/oracles/crypto-price-feeds/src/exchanges/binance.rs, apps/oracles/crypto-price-feeds/src/exchanges/binance_us.rs, apps/oracles/crypto-price-feeds/src/exchanges/bitfinex.rs, apps/oracles/crypto-price-feeds/src/exchanges/bitget.rs, apps/oracles/crypto-price-feeds/src/exchanges/bybit.rs, apps/oracles/crypto-price-feeds/src/exchanges/coinbase.rs, apps/oracles/crypto-price-feeds/src/exchanges/crypto_com_exchange.rs, apps/oracles/crypto-price-feeds/src/exchanges/gate_io.rs, apps/oracles/crypto-price-feeds/src/exchanges/gemini.rs, apps/oracles/crypto-price-feeds/src/exchanges/kraken.rs, apps/oracles/crypto-price-feeds/src/exchanges/kucoin.rs, apps/oracles/crypto-price-feeds/src/exchanges/mexc.rs, apps/oracles/crypto-price-feeds/src/exchanges/okx.rs, apps/oracles/crypto-price-feeds/src/exchanges/upbit.rs, apps/oracles/crypto-price-feeds/src/fetch_prices.rs, apps/oracles/gecko-terminal/src/lib.rs, apps/oracles/stock-price-feeds/Cargo.toml, apps/oracles/stock-price-feeds/spin.toml, apps/oracles/stock-price-feeds/src/fetch_prices.rs, apps/oracles/stock-price-feeds/src/lib.rs, apps/oracles/stock-price-feeds/src/providers/alpha_vantage.rs, apps/oracles/stock-price-feeds/src/providers/mod.rs, apps/oracles/stock-price-feeds/src/providers/yahoo_finance.rs, apps/oracles/stock-price-feeds/src/types.rs, apps/oracles/stock-price-feeds/src/utils.rs, config/feeds_config_v2.json, libs/sdk/src/http.rs, libs/sdk/src/traits/prices_fetcher.rs
This PR introduces the first functional version of the `stock-price-feeds` oracle.
---
- Implements the main oracle pipeline:
- Fetches data from multiple providers concurrently.
- Computes VWAP from provider-level price points.
- Outputs payloads in the standard `blocksense-sdk` format.
- Adds support for two providers:
- **AlphaVantage** ( end-of-day data, little daily requests )
- **YahooFinance** ( real-time data )
Both fetchers read their respective API keys from the `capabilities` section of `Settings`.
---
- Generalizes the `PricesFetcher` trait to accept an optional `api_key`.
- Introduces a helper `get_api_key(...)` to extract provider credentials.
- Adds support for optional HTTP headers in `http_get_json(...)`.
---
- Adds initial feed configuration to `spin.toml` and …
=> [oracles]: Implement initial version of `stock-price-feeds` oracle

nix/modules/blocksense/backends/systemd.nix
Quoting from the systemD man page:
```
`Restart= `
Configures whether the service shall be restarted when the service process exits, is killed, or a timeout is reached. (..)
If set to no (the default), the service will not be restarted
```
https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Restart=
We need to set the restart condition to always, to handle the scenario where one of our services may erroneously exit with code 0 (our services are meant to be continuously running and there are no case where we would expect any of them to “finish successfully”).
=> fix(services): Change service restart policy from "on-failure" to "always"

apps/nft.blocksense.network/app/layout.tsx, apps/nft.blocksense.network/components/MintForm.tsx
In reference to [[nft]: Add Google Tag Manager with Next.js](https://github.com/blocksense-network/blocksense/pull/1285)
- add `GoogleAnalytics` and `gaID`
- send two GA events - `mintButtonClicked` & `mintedNFT` with `xHandle`, `discord` and `retweetCode` parameters
=> [nft]: Add `GoogleAnalytics` and send events

libs/ts/contracts/README.md, libs/ts/contracts/contracts/AggregatedDataFeedStore.sol, libs/ts/contracts/contracts/cl-adapters/CLAggregatorAdapter.sol, libs/ts/contracts/contracts/cl-adapters/registries/CLFeedRegistryAdapter.sol, libs/ts/contracts/contracts/libraries/ADFS.sol, libs/ts/contracts/contracts/libraries/Blocksense.sol, libs/ts/contracts/contracts/libraries/CLAdapterLib.sol, libs/ts/contracts/contracts/test/AggregatedDataFeedStoreGeneric.sol, libs/ts/contracts/contracts/test/examples/BlocksenseADFSConsumer.sol, libs/ts/contracts/contracts/test/examples/RawCallADFSConsumer.sol, libs/ts/contracts/tasks/test-multichain-deploy.ts, libs/ts/contracts/test/AggregatedDataFeedStore.test.ts, libs/ts/contracts/test/CLAggregatorAdapter.test.ts, libs/ts/contracts/test/UpgradeableProxyADFS.test.ts, libs/ts/contracts/test/examples/CLFeedRegistryAdapterConsumer.test.ts, libs/ts/contracts/test/examples/FeedStoreConsumer.test.ts, libs/ts/contracts/test/examples/utils/feedStoreConsumer.ts, libs/ts/contracts/test/utils/helpers/common.ts, libs/ts/contracts/test/utils/helpers/compareGasWithExperiments.ts, libs/ts/contracts/test/utils/wrappers/adfs/ADFSBase.ts, libs/ts/contracts/test/utils/wrappers/adfs/ADFSBaseGeneric.ts, libs/ts/contracts/test/utils/wrappers/chainlink/Base.ts, libs/ts/contracts/test/utils/wrappers/interfaces/IADFSWrapper.ts, libs/ts/contracts/test/utils/wrappers/types.ts
- Refactor `round` to become `index` (everywhere except CL compatibility naming)
- Optimise assembly code in libs
- Rename Blocksense lib to ADFS lib and refactor examples to combine `stride` and `feedId` so that there is no stride variable
=> Contract library optimisations

apps/oracles/eth-rpc/spin.toml, apps/oracles/eth-rpc/src/abi/YieldFiyUSD.json, apps/oracles/eth-rpc/src/lib.rs, config/feeds_config_v2.json, libs/feed_registry/src/registry.rs, libs/ts/config-types/src/data-feeds-config/oracles.ts, libs/ts/config-types/src/data-feeds-config/types.ts, nix/filesets.nix
Added yield nest price feeds:
1. report YieldFiyUSD -> exchangeRate from smart contract address https://etherscan.io/token/0x2799dE2E1e769fA58dd3787F70BcD839AF3a1F39#readProxyContract
2. Report YnBNBx from BNB chain. This requires different RPCs
3. Added a fallback mechanism in case one RPC does not return useful data
```bash
+---------+---------------------------+----------------------------------+---------------------------------------------+
| Feed ID |          Method           |              Value               |                   RPC Url                   |
+---------+---------------------------+----------------------------------+---------------------------------------------+
|  100001 | YnETHx -> convertToAssets | Numerical(1.0451593123791621e18) | …
```
=> feat(oracles): Add RPC Etherium oracle YToken echangeRate

nix/test-environments/example-setup-01.nix
1. Once on branch run: 
```
direnv reload 
```
2. Run Blocksense:
```
just start-blocksense
```
3. Examine the logs of the reporter.
Look for something like:
=> [nix/example-setup-01]: Update `eth-rpc` oracle `allowed-outbound-hosts`

Cargo.lock, apps/sequencer/Cargo.toml, apps/sequencer/bin/sequencer_runner.rs
In order to enable flamegraph generation with pprof we need to compile the sequencer with `RUSTFLAGS="--cfg tokio_unstable -C force-frame-pointers=yes" cargo build --features profile --release`. Once enabled, the sequencer will produce flamegraphs similar to this: 
to be used for performance analysis. No manual code instrumentation is needed, since the stack sampling is performed by the Linux perf subsystem via kernel APIs.
=> feat(sequencer/profiling): Provide the ability to generate flamefraphs with pprof

apps/oracles/gecko-terminal/spin.toml, config/feeds_config_v2.json
To test it run the gecko terminal oracle
`cd apps/oracles/gecko-terminal && spin up --build`
Example output:
```bash
+---------+---------------+--------------------+---------+---------------------+------------------+---------------+--------------------------------------------------------------------+
| Feed ID |    Network    |        Name        | Reverse |     Price[USD]      |   Volume[USD]    | Enough volume |                                Pool                                |
+---------+---------------+--------------------+---------+---------------------+------------------+---------------+--------------------------------------------------------------------+
| 1000007 | arbitrum      | oLP / USDC 0.424%  | false   |    1.05676688718824 |                0 |           Yes | …
```
=> feat(oracles/gecko-terminal): Add oLP price from Arbitrum

.github/SETUP.md, Justfile, README.md, scripts/dev-shell/change-devshell.sh, scripts/dev-shell/get-available-shells.sh, scripts/dev-shell/list-devshells.sh, scripts/utils/ansi.sh
This PR introduces a more ergonomic developer experience for working with multiple `nix` dev shell environments:
* **`change-devshell.sh`**: Switch between shell variants (`default`, `rust`, `js`, etc.) by updating `.env` and triggering `direnv reload`.
* **`get-available-shells.sh`**: Robust detection of available shells (via `nix develop`, fallback to flake parsing).
* **`list-devshells.sh`**: Lists all available shells, highlighting the currently active one.
* **Justfile integration**:
* `just change-devshell rust`
* `just list-devshells`
=> feat: convenient scripts for changing the current devshell (see SETUP.md)

libs/ts/onchain-interactions/src/scripts/balance-script.ts
Prometheus metrics exposed at http://0.0.0.0:9100/metrics
Before:
HELP eth_account_balance Ethereum account balance in Ether
TYPE eth_account_balance gauge
eth_account_balance{chainId="168587773",address="0xd756119012CcabBC59910dE0ecEbE406B5b952bE"} 9.465554776027217
eth_account_balance{chainId="44787",address="0xd756119012CcabBC59910dE0ecEbE406B5b952bE"} 3.4101056136289887
eth_account_balance{chainId="763373",address="0xd756119012CcabBC59910dE0ecEbE406B5b952bE"} 1.7170801628062853
Now:
HELP eth_account_balance Ethereum account balance in Ether
TYPE eth_account_balance gauge
eth_account_balance{networkName="blast-sepolia",address="0xd756119012CcabBC59910dE0ecEbE406B5b952bE",rpcUrl="https://rpc.ankr.com/blast_testnet_sepolia"} 9.465555730820917 …
=> [onchain-interactions]: Use networkName as Gauge label for prometheus

apps/docs.blocksense.network/components/DeployedContracts/DeployedContracts.tsx, apps/docs.blocksense.network/scripts/collect-deployment-artifacts.ts, apps/docs.blocksense.network/src/data-feeds/utils.ts, apps/docs.blocksense.network/src/utils-fs.ts, libs/ts/base-utils/package.json, libs/ts/base-utils/src/array-iter.spec-d.ts, libs/ts/base-utils/src/array-iter.ts, libs/ts/base-utils/src/env/functions.spec.ts, libs/ts/base-utils/src/env/functions.ts, libs/ts/base-utils/src/env/index.ts, libs/ts/base-utils/src/env/layered-config.ts, libs/ts/base-utils/src/evm/functions.spec-d.ts, libs/ts/base-utils/src/evm/functions.spec.ts, libs/ts/base-utils/src/evm/functions.ts, libs/ts/base-utils/src/evm/networks.ts, libs/ts/base-utils/src/fs.ts, libs/ts/base-utils/src/string.test.ts, libs/ts/base-utils/src/string.ts, libs/ts/base-utils/src/tty.ts, libs/ts/base-utils/src/type-level.spec-d.ts, libs/ts/base-utils/src/type-level.ts, libs/ts/config-types/src/data-feeds-config/types.ts, libs/ts/config-types/src/evm-contracts-deployment/index.ts, libs/ts/config-types/src/read-write-config.ts, libs/ts/contracts/tasks/multichain-deploy.ts, package.json
This pull request introduces a powerful, type-safe, and hierarchical system for parsing environment variable configurations, primarily aimed at simplifying multi-network EVM deployments. It adds new core functionality to the `@blocksense/base-utils/env` module and a rich set of supporting utilities.
Managing deployment configurations across numerous networks (e.g., `local`, `ethereum-sepolia`, `arbitrum-mainnet`) can be cumbersome. Configuration parameters often have default values but need to be overridden for specific network types (testnet vs. mainnet) or for individual networks. This leads to complex, hard-to-maintain, and error-prone deployment scripts.
A new layered configuration parser is introduced. The core functions are:
-   `parseLayeredEnvConfig`: A generic function for …
=> feat(base-utils): Add type-safe, layered environment variable parser for deployments

.cargo/config.toml
Since the performance cost of enforcing frame pointers is not significant and is beneficial for debugging and perf monitoring we enable it by default.
=> build(blocksense): Enable force-frame-pointers=yes by default

.envrc
The default version of find (`/usr/bin/find`) doesn't support `-p`.
Additionally the `watch_file` function sometimes is not able to accept long list of files.
=> fix(direnv): Fix direnv on macOS systems with old version of `find`

.gitignore, Justfile, libs/ts/base-utils/package.json, libs/ts/contracts/hardhat.config.ts, libs/ts/contracts/package.json, libs/ts/contracts/tasks/deployment-utils/access-control.ts, libs/ts/contracts/tasks/deployment-utils/deploy-contracts.ts, libs/ts/contracts/tasks/deployment-utils/deploy-multisig.ts, libs/ts/contracts/tasks/deployment-utils/init-chain.ts, libs/ts/contracts/tasks/deployment-utils/multisig-tx-exec.ts, libs/ts/contracts/tasks/deployment-utils/register-cl-adapters.ts, libs/ts/contracts/tasks/deployment-utils/upgrade-proxy-implementation.ts, libs/ts/contracts/tasks/index.ts, libs/ts/contracts/tasks/ms-change-sequencer.ts, libs/ts/contracts/tasks/multichain-deploy.ts, libs/ts/contracts/tasks/test-multichain-deploy.ts
This PR refactors all remaining Hardhat tasks into regular TypeScript functions.
> Note: This is another part of https://github.com/blocksense-network/blocksense/pull/1236
* Replaced all `HardhatTaskDefinition`s (e.g. `deploy-contracts`, `deploy-multisig`, `upgrade-proxy-implementation`, etc.) with regular async functions.
* Updated scripts to call these functions directly.
* Cleaned up related imports and project config.
* Ensured `typechain` outputs are properly exported to support both `require()` and `import()` usage.
* Introduced a new `just deploy-evm-contracts` command for streamlined deployment.
=> [contracts]: Convert hh task to functions and some other improvements

apps/sequencer/src/providers/eth_send_utils.rs
Use with_nonce instead of nonce in transaction builder + additional logging.
=> fix(sequencer/eth_send_utils): Use with_nonce instead of nonce when creating a tx with alloy

Justfile, nix/shells/pkg-sets/dev-shell.nix, nix/test-environments/default.nix
This PR introduces a new set of developer commands to streamline working with `process-compose'- based infrastructure environments.
* `list-environments`: Lists all available environments using `nix eval`.
* `build-environment`: Builds one or all environment definitions via Nix and copies the result to `config/generated/process-compose/`.
* `start-environment`: Shorthand for running `run-<env>` scripts (which are auto-generated via the Nix flake).
```bash
just list-environments
```
Example output:
```
example-setup-01
example-setup-02
example-setup-03
```
---
```bash
just build-environment <environment>
```
Builds the `process-compose` config for the specified environment and copies the result to `config/generated/process-compose/`.
Example:
```bash
just build-environment example-setup-01 …
```
=> Add support for managing `process-compose` environments via `just`

Justfile, nix/test-environments/default.nix
* Removed `runEnvironments` from `nix/test-environments/default.nix`.
These shell script wrappers (e.g., `run-example-setup-02`) are no longer generated via Nix.
* Updated the `start-environment` Justfile command to:
* Build the relevant YAML file if it doesn’t already exist.
* Directly invoke `process-compose -f <env>.yaml` rather than relying on `run-<env>` scripts.
* Introduced a `PROCESS_COMPOSE_ARTIFACTS_DIR` constant for reuse.
=> [just]:  Refactor process-compose environment runner: remove Nix-generated `run-<env>` scripts

apps/sequencer/src/block_creator.rs, libs/data_feeds/src/feeds_processing.rs
In order to take advantage of the cost reduction on updating the round counters of the batched feeds, we sort them by feed id. This way in case we produce more updates than can fit a block and we split them in sets, those sets will have adjacent feed id updates and will not need to update the same memory elements for the round indexes.
=> refactor(sequencer/feeds): Sort the batch of feed updates by feed id

Justfile, nix/test-environments/default.nix
This PR introduces two cleanup refactors to improve naming clarity and consistency when working with process-compose environments, addressing the latest review of https://github.com/blocksense-network/blocksense/pull/1439.
Also introduces [groups](https://github.com/casey/just#groups) and [documentation-comments](https://github.com/casey/just?tab=readme-ov-file#documentation-comments) to the just commands
* Replaces the shell-style constant `PROCESS_COMPOSE_ARTIFACTS_DIR` with a more idiomatic Just variable: `process-compose-artifacts-dir`.
* Uses `root-dir` for consistent path resolution instead of relying on `$GIT_ROOT`.
* Changes the generated artifact filenames from `<env>-process-compose.yaml` to `process-compose-<env>.yaml`.
* This affects both the Nix environment generator …
=> [just/nix] Cleanup refactors related to process-compose environments. Improvements in Justfile

Justfile, apps/changelog-generator/package.json, apps/changelog-generator/src/Cli.ts, apps/changelog-generator/src/bin.ts, apps/changelog-generator/src/commands/list-feeds.ts, apps/changelog-generator/tsconfig.json, apps/changelog-generator/tsconfig.scripts.json, apps/changelog-generator/tsconfig.src.json, apps/changelog-generator/tsconfig.test.json, libs/ts/base-utils/src/tty.ts, libs/ts/config-types/src/read-write-config.ts, yarn.lock
This is a preview how to add simple command within `Effect CLI app` and how to run the command.
Run the following command in the `/apps/changelog-generator/`:
```
yarn start list-feeds --network <network>
```
where `<network>` is for example: `ink-sepolia`, `citrea-testnet`, etc.
As a result you should see a table containing `feed name`, `address`, `decimals`, `base` and `quote` for each available feed. 
The output of running the above mentioned command is:
Additionally you can run
```
yarn start list-feeds --wizard
```
where you enter the interactive mode of the CLI app. The result is shown below:
[![asciicast](https://asciinema.org/a/0eDUR1Q9ci77CagSUPpOFClkl.svg)](https://asciinema.org/a/0eDUR1Q9ci77CagSUPpOFClkl)
Apart from that, in the `/apps/changelog-generator/` you can run the …
=> [changelog-generator]: Add `list feeds` command

libs/ts/contracts/contracts/UpgradeableProxyADFS.sol
New salt:
- local `0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266` for multisig `0x2DCe5D714Fe5eAE59a59940D0f5365F211110a05`: **`0xc1945d492a891c2a334d9396a470f5ccf294f0c5e0c7b4ebd0a4caba75788762`** -> `0xADF5aad5678f80110f9Ead077D91817bDde235Bc`
- testnet `0xd756119012CcabBC59910dE0ecEbE406B5b952bE` for multisig `0x53AdbDAA3EE8725De80Bf97173B1f1A0a48036De`: **`0x2c8218120b56642dfe422ab6fea501f3addf867d6e9ac8335abcba33ec033f5d`** -> `0xADF5aab911b08C78688CafcD865b605101a840E7`
- mainnet `0x421D7821121AE6e17C3dB72Cb5635Cc62df5F8aa` for multisig `0xe029f9EE758c61Ec8613c8a4F1122239d96473eb`: **`0x9a86ab80c0e8777c9de8cca57d101ad892f096d265e0cc068a207ed1ab616a25`** -> `0xADF5aaeB747a2797b45bca4e3C0c6C8bBDAfBf27`
=> refactor(contracts): Remove block number from upgradeable proxy natspec

nix/test-environments/example-setup-01.nix
Saw the following log when testing oracles
=> [nix/example-setup-01]: Add missing `allowed-outbound-host` of `eth-rpc`

libs/ts/nextra-theme-docs/src/components/sidebar.tsx
This PR aims to fix the issues with sidebar not expanding properly after collapse.
* **Before :**
* **After :**
=> [docs.ws]: Fix sidebar expand/collapse behavior

apps/trigger-oracle/src/lib.rs
[BSN-3284: Remove component tracing from `trigger-oracle`](https://coda.io/d/_d6vM0kjfQP6#_tuk5j/r3284&view=full)
=> [trigger-oracle]: Remove component tracing 

Justfile, apps/avm-relayer/package.json, apps/avm-relayer/test/relayer.test.ts, apps/chain-interactions/package.json, apps/changelog-generator/package.json, apps/data-feeds-config-generator/package.json, apps/docs.blocksense.network/package.json, apps/e2e-tests/package.json, libs/ts/base-utils/package.json, libs/ts/base-utils/src/array-iter.spec-d.ts, libs/ts/base-utils/src/array-iter.spec.ts, libs/ts/base-utils/src/array-iter.ts, libs/ts/config-types/package.json, libs/ts/contracts/package.json, libs/ts/onchain-interactions/package.json, libs/ts/ui/package.json, yarn.lock
This PR introduces several improvements to the `base-utils` package and enhances the testing infrastructure by enabling code coverage reporting and improving CI stability.
---
The `@blocksense/base-utils` package has been updated with new object manipulation utilities, better documentation, and increased test coverage.
* **New Utility Functions**:
* `mapValues`: Creates a new object by transforming the values of the original.
* `mapEntries`: Creates a new object by transforming both keys and values.
* `filterEntries`: Provides type-safe filtering of an object's entries based on key and value predicates.
* `mapValuePromises`: Asynchronously maps object values to promises and resolves them into a new object.
* **Improved Test Coverage**: Added comprehensive tests for existing utilities …
=> feat(base-utils): Add `mapValues`, `mapEntries`, `filterEntries`, and `mapValuePromises` and enable test coverage

apps/e2e-tests/package.json, apps/e2e-tests/src/process-compose/e2e.spec.ts, config/feeds_config_v2.json, nix/test-environments/example-setup-03.nix, yarn.lock
This PR introduces end-to-end tests for validating the sequencer configuration and ensuring feed prices are actively updated. Key changes include:
* ✅ **Added** test to fetch and validate sequencer config.
* ✅ **Introduced** new test to assert price updates across allowed feeds.
* ✅ **Created** `getPricesInfo` utility for streamlined onchain price retrieval.
* 🔧 **Refactored** test environment (`example-setup-03`) to remove feeds not suitable for fast e2e tests (e.g., slow or unsupported due to missing API keys).
* 🛠️ **Fixed** incorrect decimals for feed `100002 - YUSD / USDC`.
* ⬆️ **Upgraded** `effect` from `3.7.0` to `3.15.1` in `e2e-tests`.
* 📦 **Installed** `@blocksense/contracts` dependency to support onchain queries in tests.
[BSN-3279: Use Viem wrappers to read data from RPCs …
=> [e2e-test]: Add sequencer config and price update tests. Update `example-setup-03`.

apps/e2e-tests/src/process-compose/config/feeds_config_v2.json, apps/e2e-tests/src/process-compose/helpers.ts, nix/modules/blocksense/backends/process-compose.nix
This PR improves configuration flexibility for the Blocksense `process-compose` environment by allowing the `FEEDS_CONFIG_DIR` to be supplied via an environment variable, and introduces a new `feeds_config_v2.json` for use in E2E tests.
* **Nix module (`process-compose.nix`)**
* Replaces hardcoded `FEEDS_CONFIG_DIR` path with a dynamic value using `builtins.getEnv` + fallback to `${config.devenv.root}/config`.
* This allows overriding the feed config path at evaluation time (requires running with `--impure`).
* **E2E test setup**
* Adds a new `feeds_config_v2.json` file.
* Updates `startEnvironment` helper to explicitly set the `FEEDS_CONFIG_DIR` via the environment using `execa`.
To override the feeds config path, set the environment variable before running:
```sh …
```
=> [nix/process-compose/e2e-tests]: Make FEEDS_CONFIG_DIR configurable via environment variable

apps/e2e-tests/src/process-compose/e2e.spec.ts, nix/test-environments/example-setup-03.nix
This PR introduces end-to-end tests for pegged asset functionality and simplifies feed configuration in the E2E test environment by:
* Adding logic to automatically collect feed IDs from the feeds config when `allow-feeds` is an empty array.
* Refactoring the test environment setup to reduce unnecessary feed declarations.
* Testing price behavior of pegged assets with differing tolerance levels.
---
*  Added support in `e2e.spec.ts` to:
* Load feed config from `/get_feeds_config` if `allow_feeds` is empty.
* Add assertion logic to test pegging:
* Feed `50000` (USDT) with **10% tolerance** is expected to remain pegged.
* Feed `50001` (USDC) with **0.000001% tolerance** is expected **not** to be pegged.
* Cleaned up excessive `allow-feeds` and `publishing-criteria` blocks.
* Retained only …
=> [example-setup-03/e2e-tests]:  Add pegging tests and simplify feed configuration

Justfile, apps/e2e-tests/@types/parse-prometheus-text-format.d.ts, apps/e2e-tests/package.json, apps/e2e-tests/src/utils/metrics/index.ts, apps/e2e-tests/src/utils/metrics/metrics-fetcher.spec.ts, apps/e2e-tests/src/utils/metrics/metrics-fetcher.ts, apps/e2e-tests/src/utils/metrics/types.ts, apps/e2e-tests/tsconfig.json, libs/ts/base-utils/package.json, package.json, tsconfig.base.json, yarn.lock
---
This PR introduces a utility to fetch and parse Prometheus metrics in the `e2e-tests` package. It enables end-to-end tests to programmatically access and validate metrics exposed by services, supporting better observability and test automation.
---
- **`getMetrics(url)`**:
- Fetches raw metrics from a Prometheus-compatible `/metrics` endpoint.
- Parses Prometheus text format using `parse-prometheus-text-format`.
- Validates data structure using `effect` schemas.
- **Robust error handling** with:
- `HttpClientError.HttpClientError` (from `HttpClientError`, `@effect/platform`)
- `ParseMetricsError` (our custom error for handling 3rd party call)
- `ParseError` (from `effect`)
- Added unit tests in `metrics-fetcher.spec.ts` covering:
- ✅ Successful fetch & parse
- ❌ Network failure
- ❌ …
=> [e2e-tests]: Implement Prometheus metrics fetcher utility

Justfile, apps/e2e-tests/package.json, apps/e2e-tests/src/process-compose/e2e.spec.ts, apps/e2e-tests/src/process-compose/helpers.ts, apps/e2e-tests/src/process-compose/types.ts, yarn.lock
This PR refactors the `e2e.spec.ts` end-to-end tests to fully utilize the `effect` library for handling asynchronous operations and effects, improving composability and test clarity. Additionally, it installs and integrates the `@effect/vitest` testing utilities to enable effect-aware test definitions and better integration with Vitest.
- Rewrote `apps/e2e-tests/src/process-compose/e2e.spec.ts`:
- Replaced traditional async/await and direct promises with Effect-based `Effect.gen`, `Effect.promise`, and other combinators.
- Introduced `Effect`-based service abstractions (`ProcessCompose`, `Sequencer`, `LogChecker`) in a new `types.ts` file for cleaner dependency injection.
- Replaced manual environment startup/shutdown (`startEnvironment`, `stopEnvironment`) with Effect-provided services. …
=> [e2e-tests]: Refactor e2e tests' infrastructure with `Effect`

nix/modules/blocksense/backends/process-compose.nix, nix/shells/pkg-sets/rust.nix
- Leads to the breakage of all in-shell applications which originally
link to (usually) older versions of the libraries in `LD_LIBRARY_PATH`
(biggest offender being `nix` itself with `libcurl`)
- Set `LD_LIBRARY_PATH` for the sequencer and reporters manually in the
`process-compose` configuration
(they were previously inheriting it from the shell)
=> fix(nix): Do not set `LD_LIBRARY_PATH` in the rust `devShell`

apps/e2e-tests/src/process-compose/e2e.spec.ts, apps/e2e-tests/src/process-compose/types.ts
[BSN-3326: Use getSingleDataAtIndex at the e2e tests](https://coda.io/d/_d6vM0kjfQP6#_tuk5j/r3326&view=full)
=> [e2e-tests]: Use `getSingleDataAtIndex` at the e2e tests

apps/e2e-tests/src/process-compose/e2e.spec.ts, apps/e2e-tests/src/process-compose/helpers.ts, apps/e2e-tests/src/process-compose/types.ts, apps/e2e-tests/src/utils/onchain.spec.ts, apps/e2e-tests/src/utils/onchain.ts, libs/ts/contracts/lib/viem/ContractConsumerBase.ts, nix/test-environments/example-setup-03.nix
This PR improves the E2E test suite to reflect the sequencer’s new round-preserving behavior when publishing feed updates. It also introduces a utility to simplify on-chain data retrieval and includes small refactors and internal improvements.
---
* Updated E2E test to expect feed rounds to increase from the initial round rather than being reset.
* Introduced a check that the original round is *not* overwritten after sequencer restart.
* Removed `should-load-round-counters = false` from the test Nix setup to enable proper round loading.
* Assign `sequencer: SequencerService` in beforeAll
* Fetch initial on-chain feeds info in beforeAll to avoid race with local updates
Move retrieval of initial on-chain feed state into the `beforeAll` phase
via new helper `getInitialFeedsInfoFromNetwork`. …
=> [e2e-tests]:  Utilize sequncer round parsing logic

libs/ts/config-types/package.json, libs/ts/contracts/tasks/add-signer-to-multisig.ts, libs/ts/contracts/tasks/ms-change-sequencer.ts, libs/ts/contracts/tasks/multichain-deploy.ts, libs/ts/contracts/tasks/test-multichain-deploy.ts, libs/ts/contracts/tasks/verify.ts
Fixing an issue where hardhat is incompatible with the new modules introduced in the following [commit](https://github.com/blocksense-network/blocksense/commit/121b85838c42ab514cafc2ee9038c6302fddb379).
**Note: We should use full path for imports.**
On root level:
```
just clean
yarn
cd libs/ts/contracts
yarn hardhat run ./scripts/chainlink-event-fetcher.ts
```
=> [config-types]: Use strict imports from `config-types`

apps/e2e-tests/src/process-compose/e2e.spec.ts, apps/e2e-tests/src/process-compose/types.ts
Add `fetchHistory` method to the `Sequencer` service and enhance E2E tests to validate feed values against data from the `/get_history` endpoint.
- **Sequencer Service**
- Added `fetchHistory` method for retrieving aggregated feed history.
- Introduced `FeedAggregateHistorySchema` for type-safe parsing of history data.
- Integrated `fetchAndDecodeJSONEffect` for history data fetching.
- **E2E Tests**
- Updated tests to compare current feed values with corresponding historical values.
- Applied proper decimal handling during value comparison.
[BSN-3328: Compare network values to the result of get_history endpoint](https://coda.io/d/_d6vM0kjfQP6#_tu4Kik5j/r3328&view=full)
=> [e2e-tests]: Compare network values to the values from `get_history` endpoint

apps/oracles/eth-rpc/src/lib.rs, apps/oracles/gecko-terminal/src/lib.rs, apps/oracles/spout-rwa/src/lib.rs, apps/trigger-oracle/src/main.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/binance.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/binance_us.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/bitfinex.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/bitget.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/bybit.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/coinbase.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/crypto_com_exchange.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/gate_io.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/gemini.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/kraken.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/kucoin.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/mexc.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/okx.rs, libs/data_providers_sdk/src/price_data/fetchers/exchanges/upbit.rs, libs/data_providers_sdk/src/price_data/fetchers/stock_markets/alpaca_markets.rs, libs/data_providers_sdk/src/price_data/fetchers/stock_markets/alpha_vantage.rs, libs/data_providers_sdk/src/price_data/fetchers/stock_markets/fmp.rs, libs/data_providers_sdk/src/price_data/fetchers/stock_markets/twelvedata.rs, libs/data_providers_sdk/src/price_data/fetchers/stock_markets/yahoo_finance.rs, libs/sdk/src/http.rs
* Make error handling in Coinbase and Gemini better: `bail!` if no prices fetched, log otherwise
* Don't log `payload.endpoint_url` in trigger oracle timing out proxy, but only the scheme and host of the url
* Optional use proxy for http_get_json & http_post_json in `sdk/http.rs`
=> Fix oracle scripts

Justfile, nix/test-environments/example-setup-03.nix
This PR reverts a previous change that caused issues with process-compose port handling and adds a safeguard for empty `available-ports` files.
1. **Justfile**
* **Reverts commit `48151c2`** to fix unwanted port file behaviour.
* Drops unnecessary `git add` of the generated `available-ports` file.
* Adds `--impure` to `nix eval` and `nix build` so environments resolve correctly.
* This is a **temporary workaround** until we implement a proper port parsing solution.
2. **example-setup-03.nix**
* Reads ports from the generated `available-ports` file.
* Falls back to `[8547]` only when the file is empty, not just missing.
* Prevents environments from silently failing when the file exists but has no entries.
=> [nix/just]: Revert Justfile change of removing `--impure` and handle empty available-ports

nix/modules/blocksense/backends/process-compose.nix, nix/shells/pkg-sets/rust.nix
Remove `spinWrapped` from `rust.nix` to slim the dev environment. Inject
its `PATH` only for reporter processes (when not using local cargo
result) in process-compose.nix. Also drop unused blama inherit.
Benefits:
* Smaller closure / faster nix develop
* Fewer implicit tools in base shell
* Keeps reporter workflow working via conditional PATH injection
* `direnv reload`
* `just start-environment example-setup-01`
* `just start-oracle cex-price-feeds --hermetic`
* `just start-oracle cex-price-feeds --use-local-cargo-artifacts`
```
nix run $GIT_ROOT#spinWrapped
```
=> build(nix/shells): Drop `spin` from `rust` (and `default`) shells

libs/ts/base-utils/package.json, libs/ts/base-utils/src/tty.ts, yarn.lock
Revert "fix(base-utils/tty/getTextWidth): Replace our hand-rolled impl w/ `string-width` npm library"
This reverts commit b378a5d5e47ca72a7a9a494c4bd4d994abf6b9f2 as it broke hardhat.
=> [base-utils/tty/getTextWidth]: Fix compatibility with hardhat (ts-node)

.github/workflows/ci.yml, .github/workflows/on-main.yml, apps/e2e-tests/src/process-compose/e2e.spec.ts, apps/e2e-tests/vitest.config.js, nix/test-environments/example-setup-01.nix, nix/test-environments/example-setup-03.nix
We’ve updated Anvil’s RPCs to use alchemy. As a result, the sequencer now takes longer to start—about 60 seconds compared to 20 seconds previously with the old fork-url. This caused the end-to-end tests to time out, so I adjusted the timeouts to account for the slower sequencer startup.
****
=> [e2e-tests]: Setup anvil to use alchemy RPCs

libs/ts/base-utils/src/tty.ts
This pull request updates the logic for calculating text width in the `getTextWidth` function within `libs/ts/base-utils/src/tty.ts`. The main improvement is to ensure that certain whitelisted symbols, such as '₮', are always treated as single-width characters, regardless of their Unicode properties. This change helps maintain consistent alignment and formatting when displaying text containing these symbols.
Text width calculation improvements:
* Added a `whitelistedSymbols` array to explicitly include symbols (e.g., '₮') that should be treated as single-width characters.
* Modified the condition in `getTextWidth` to check for whitelisted symbols and treat them as single-width, improving text alignment for these cases.
=> [base-utils]: Add whitelist for special symbols

apps/e2e-tests/src/process-compose/e2e.spec.ts
This pull request improves the robustness of the E2E testing process by adding handling for the `SIGINT` signal (typically triggered by Ctrl+C) in the `process-compose` test suite. The main change ensures that if the tests are interrupted, the `processCompose` service is properly stopped before the process exits, preventing potential resource leaks or inconsistent states.
**Process termination handling:**
* Added a listener for the `SIGINT` signal to gracefully stop the `processCompose` service if it has started, ensuring cleanup before exiting the process. If `processCompose` hasn't started, the process simply exits. (`apps/e2e-tests/src/process-compose/e2e.spec.ts`)tests execution
=> [e2e-tests]: Kill `process-compose` when `SIGINT` is caught during tests execution

apps/oracles/Cargo.lock, apps/oracles/Cargo.toml, apps/oracles/commodities-price-feeds/Cargo.toml, apps/oracles/commodities-price-feeds/spin.toml, apps/oracles/commodities-price-feeds/src/domain.rs, apps/oracles/commodities-price-feeds/src/fetch_prices.rs, apps/oracles/commodities-price-feeds/src/lib.rs, apps/oracles/commodities-price-feeds/src/logging.rs, apps/oracles/forex-price-feeds/spin.toml, apps/oracles/forex-price-feeds/src/fetch_prices.rs, config/feeds_config_v2.json, libs/ts/config-types/src/data-feeds-config/oracles.ts, libs/ts/config-types/src/data-feeds-config/types.ts, nix/pkgs/default.nix, nix/test-environments/example-setup-01.nix
This pull request introduces a new dedicated oracle component for fetching metal prices, specifically moving the LME Copper (LME-XCU) price feed from the existing `forex-price-feeds` oracle to a new `commodities_price_feeds` oracle. The changes include setting up the new component, updating configuration and build files, and cleaning up the `forex-price-feeds` logic to remove commodities-related code.
[BSN-3417: Write custom oracle for Tellura ](https://coda.io/d/_d6vM0kjfQP6#_tu4Kik5j/r3417&view=full)
=> [oracles/commodities_price_feeds]: Oracle for Commodities

apps/e2e-tests/src/process-compose/e2e.spec.ts, libs/feed_registry/src/types.rs
****
This pull request improves error handling for feed results by introducing support for the `UndefinedError` variant across both backend Rust code and frontend TypeScript tests. The main focus is on ensuring that the system can properly serialize and deserialize the new error type, and that end-to-end tests cover this scenario.
**Error handling improvements:**
* Added support for `UndefinedError` in the `FeedError` enum and implemented custom deserialization logic in `libs/feed_registry/src/types.rs` to handle both object and string representations of this error.
* Removed the unnecessary `Deserialize` derive from the `FeedError` enum and replaced it with a manual implementation to accommodate the new error variant.
**Testing enhancements:**
* Updated the E2E test suite in …
=> [e2e-tests]: Add support for `UndefinedError` report result

apps/sequencer/src/providers/provider.rs, libs/feeds_processing/src/adfs_gen_calldata.rs
- Fix to correctly wrap around the round counters when serializing them.
- Add unit test that has one Feed ID with update counter larger than the round buffer size to recreate problem.
- Refactor unit test setup to pass as arguments to initialization function the updates, round counters and strides per feed.
=> fix(sequencer/adfs): Fix to correctly wrap around the round counters when serializing them + unit test

.github/workflows/ci.yml, apps/docs.blocksense.network/components/DataFeeds/Cards/NetworkAccessCard.tsx, apps/docs.blocksense.network/components/DeployedContracts/NetworkIcon.tsx, apps/docs.blocksense.network/package.json, apps/docs.blocksense.network/src/utils.ts, apps/docs.blocksense.network/tests/network-icons.spec.ts
This pull request improves how network icons are handled and tested in the `docs.blocksense.network` app. It introduces a utility function to consistently map network names to icon filenames, updates components to use this function, and adds automated testing to ensure all deployed networks have corresponding icon images. It also updates the CI workflow to run these new tests.
**Network Icon Handling Improvements:**
* Added a new utility function `networkNameToIconName` in `utils.ts` to standardize mapping from `NetworkName` to icon filenames, replacing previous string splitting logic.
* Updated `NetworkIcon` components in `NetworkAccessCard.tsx` and `NetworkIcon.tsx` to use the new `networkNameToIconName` utility for determining icon image paths.
**Testing and CI Integration:**
* Added a …
=> [docs.ws/gh-actions]: Test deployed networks icons
